VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IOfficeDocument"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public includeInstalled As Boolean ' also find fonts already installed on the system

Public Function GetFonts(ByVal objFile As Object) As Collection
' no code allowed
End Function

